spring:
  application:
    name: plan-your-trip-core
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5440/plan_your_trip}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port: 8080

logging:
  level:
    root: info
    web: debug
    org.springframework.web: debug
    com.planyourtrip.core: ${LOGGING_LEVEL:debug}
    com.zaxxer.hikari.pool: ${HIKARI_LOGGING_LEVEL:debug}