version: '3.9'
name: plan-your-trip

services:
  plan-your-trip-postgres:
    image: 'postgres:14-alpine'
    container_name: plan-your-trip-postgres
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: plan_your_trip
